### ISSUE TITLE
Uncaught TypeError: Cannot read property 'length' of undefined

### ISSUE THREAD

**Issue by goruha** [mb3online/atom-snippet-manager#16]
[Enter steps to reproduce:]

1. Open Packages->Snippet Manager->Toggle

**Atom**: 1.26.1 x64
**Electron**: 1.7.11
**OS**: Ubuntu 14.04.5
**Thrown From**: [snippet-manager](https://github.com/mb3online/atom-snippet-manager) package 1.2.0

### Stack Trace

Uncaught TypeError: Cannot read property 'length' of undefined

```
At /home/goruha/.atom/packages/snippet-manager/lib/manager.js:181

TypeError: Cannot read property 'length' of undefined
    at /packages/snippet-manager/lib/manager.js:181:35
    at FSReqWrap.oncomplete (fs.js:114:15)
```

### Commands

```
     -2:30.7.0 markdown-writer:indent-list-line (input.hidden-input)
     -0:11.8.0 snippet-manager:toggle (input.hidden-input)
```

### Non-Core Packages

```
atom-csv-markdown 1.0.2 
atom-hugo 0.1.2 
busy-signal 1.4.3 
document-outline 2.1.1 
hugofy 2.0.0 
intentions 1.1.5 
language-hugo 0.5.1 
language-markdown 0.25.1 
linter 2.2.0 
linter-markdown 5.2.1 
linter-ui-default 1.7.1 
markdown-assistant 0.2.0 
markdown-badges-snippets 0.3.1 
markdown-commander 0.1.1 
markdown-document 0.2.1 
markdown-fold 0.2.0 
markdown-folding 0.3.1 
markdown-footnote 1.1.5 
markdown-helper 0.3.0 
markdown-image-insertion 0.2.1 
markdown-image-paste 2.5.2 
markdown-img-paste 0.3.9 
markdown-it-preview 0.2.4 
markdown-pdf 2.1.0 
markdown-scroll-sync 2.1.2 
markdown-table-calc 0.4.0 
markdown-table-editor 1.1.0 
markdown-to-asciidoc 0.8.0 
markdown-toc 0.4.2 
markdown-tool 1.1.0 
markdown-up-img 1.0.1 
markdown-writer 2.7.3 
MDBP-markdown-book-preview 1.9.1 
mr-markdown-pdf 1.6.0 
nuxeo-documentation-links 0.1.0 
placehold-atom-snippet 0.2.0 
pp-markdown 0.0.2 
snippet-creator 0.2.0 
snippet-generator 0.3.2 
snippet-generator-plus 0.1.2 
snippet-manager 1.2.0 
tidy-markdown 3.0.1 
toggle-markdown-task 0.6.0 
tool-bar 1.1.7 
tool-bar-markdown-writer 0.3.1 
```

**Comment by ericadamski** [comment]
@goruha thank you for submitting an issue! I will take a look into it 😄

**Comment by ericadamski** [comment]
Is it possible your directory that you want to search in doesn't exist?
